Repository 104corp/tailwindcss, pull requests merged in 2021-07, with the labels that each got.

#20 ITGD-681 回歸使用者自己決定套用的 class
  stubs/section/b/corePlugins.js
  stubs/section/c/corePlugins.js
Labels: feature

#21 Release/v1.2.0
  package.json
  stubs/section/b/corePlugins.js
  stubs/section/c/corePlugins.js
Labels: staging

#22 ITGD-742 tailwind b config 沒有提示
  src/util/getAllConfigs.js
Labels: bug fix

#23 Release/v1.2.1
  package.json
  src/util/getAllConfigs.js
Labels: bug fix

#24 ITGD-775 修復 loading 在 IE11 的位置偏移問題
  src/plugins/guideline/bLoading.js
  src/plugins/guideline/cLoading.js
Labels: bug fix

#25 ITGD-777 調整 B button 高度
  src/plugins/guideline/bButton.js
Labels: feature

#26 Release/v1.2.2
  package.json
  src/plugins/guideline/bButton.js
  src/plugins/guideline/bLoading.js
  src/plugins/guideline/cLoading.js
Labels: staging
