Repository 104corp/tailwindcss, pull requests merged in 2021-06, with the labels that each got.

#1 ITGD-640
  __tests__/applyComplexClasses.test.js
  __tests__/defaultConfig.test.js
  __tests__/defaultTheme.test.js
  __tests__/purgeUnusedStyles.test.js
  __tests__/responsiveAtRule.test.js
  __tests__/sanity.test.js
  __tests__/screenAtRule.test.js
  __tests__/targetMode.test.js
  __tests__/variantsAtRule.test.js
  defaultConfig.js
  defaultTheme.js
  src/constants.js
  src/index.js
  src/util/getAllConfigs.js
  stubs/104.c.config.js
Labels: feature

#2 ITGD-641
  .gitignore
  package-lock.json
  yarn.lock
Labels: feature

#3 ITGD-634
  src/corePluginList.js
  src/plugins/guideline/cColor.js
  src/plugins/index.js
  stubs/104.c.config.js
Labels: feature

#8 ITGD-635 新增 component: c button
  src/corePluginList.js
  src/plugins/guideline/cButton.js
  src/plugins/index.js
  stubs/section/b/corePlugins.js
  stubs/section/c/variants.js
Labels: feature

#9 ITGD-636 新增 component: c tooltip
  src/corePluginList.js
  src/plugins/guideline/cTooltip.js
  src/plugins/index.js
  stubs/section/b/corePlugins.js
  stubs/section/c/variants.js
Labels: feature

#7 ITGD-639 新增 component: c tag
  src/corePluginList.js
  src/plugins/guideline/cTag.js
  src/plugins/index.js
  stubs/section/b/corePlugins.js
  stubs/section/c/variants.js
Labels: feature

#5 ITGD-637 新增 component: c Loading
  src/corePluginList.js
  src/plugins/guideline/cLoading.js
  src/plugins/index.js
  stubs/section/b/corePlugins.js
  stubs/section/c/variants.js
Labels: feature

#6 ITGD-638 新增 component: c dialog
  src/corePluginList.js
  src/plugins/guideline/cDialog.js
  src/plugins/index.js
  stubs/section/b/corePlugins.js
  stubs/section/c/variants.js
Labels: feature

#10 ITGD-673 移除不必要的 require
  stubs/section/b/corePlugins.js
Labels: feature

#11 ITGD-652 整併 color、tooltip、tag、dialog
  src/corePluginList.js
  src/plugins/guideline/color.js
  src/plugins/guideline/dialog.js
  src/plugins/guideline/tag.js
  src/plugins/guideline/tooltip.js
  src/plugins/index.js
  stubs/section/b/corePlugins.js
  stubs/section/b/variants.js
  stubs/section/c/corePlugins.js
  stubs/section/c/variants.js
Labels: feature

#13 ITGD-654 新增 component: b loading
  src/corePluginList.js
  src/plugins/guideline/bLoading.js
  src/plugins/index.js
  stubs/section/b/variants.js
  stubs/section/c/corePlugins.js
Labels: feature

#12 ITGD-653 新增 component: b button
  src/corePluginList.js
  src/plugins/guideline/bButton.js
  src/plugins/index.js
  stubs/section/b/variants.js
  stubs/section/c/corePlugins.js
Labels: feature

#14 ITGD-658 base、config 調整
  src/plugins/css/guidelineBase.css
  src/plugins/preflight.js
  stubs/section/b/corePlugins.js
  stubs/section/b/theme.js
  stubs/section/c/corePlugins.js
  stubs/section/c/theme.js
Labels: feature

#15 Release/v1.0.0
  .gitignore
  __tests__/applyComplexClasses.test.js
  __tests__/defaultConfig.test.js
  __tests__/defaultTheme.test.js
  __tests__/purgeUnusedStyles.test.js
  __tests__/responsiveAtRule.test.js
  __tests__/sanity.test.js
  __tests__/screenAtRule.test.js
  __tests__/targetMode.test.js
  __tests__/variantsAtRule.test.js
  defaultConfig.js
  defaultTheme.js
  package-lock.json
  package.json
  src/constants.js
  src/corePluginList.js
  src/index.js
  src/plugins/css/guidelineBase.css
  src/plugins/guideline/bButton.js
  src/plugins/guideline/bLoading.js
  src/plugins/guideline/cButton.js
  src/plugins/guideline/cLoading.js
  src/plugins/guideline/color.js
  src/plugins/guideline/dialog.js
  src/plugins/guideline/tag.js
  src/plugins/guideline/tooltip.js
  src/plugins/index.js
  src/plugins/preflight.js
  src/util/getAllConfigs.js
  stubs/104.b.config.js
  stubs/104.c.config.js
  stubs/section/b/corePlugins.js
  stubs/section/b/theme.js
  stubs/section/b/variants.js
  stubs/section/c/corePlugins.js
  stubs/section/c/theme.js
  stubs/section/c/variants.js
  yarn.lock
Labels: staging

#16 ITGD-562 修改上傳的 file
  package.json
Labels: bug fix

#18 ITGD-670 b & c icon 整併
  common/fonts/font.css
  common/fonts/font.json
  common/fonts/icomoon.eot
  common/fonts/icomoon.svg
  common/fonts/icomoon.ttf
  common/fonts/icomoon.woff
  package.json
  src/corePluginList.js
  src/plugins/guideline/icon.js
  src/plugins/index.js
  stubs/section/b/variants.js
  stubs/section/c/variants.js
Labels: feature

#17 Release/v1.0.1
  package.json
Labels: staging

#19 Release/v1.1.0
  common/fonts/font.css
  common/fonts/font.json
  common/fonts/icomoon.eot
  common/fonts/icomoon.svg
  common/fonts/icomoon.ttf
  common/fonts/icomoon.woff
  package.json
  src/corePluginList.js
  src/plugins/guideline/icon.js
  src/plugins/index.js
  stubs/section/b/variants.js
  stubs/section/c/variants.js
Labels: staging
